# Configuration for GitHub issue templates

blank_issues_enabled: false

contact_links:
  - name: âœˆï¸ Telegram Support
    url: https://t.me/ByteHavenPro
    about: Join for feature request or report bug inside Telegram.
  - name: ğŸ”° Security Vulnerabilities
    url: https://github.com/sang765/ReBypass/security/advisories
    about: Please report security vulnerabilities here.
